prometheus-community/promql-langserver

doc/proposals/2019_generated promql parser.md

Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

docs/proposals: clean up parser proposal

---

README.md
langserver/cache/compile.go
langserver/cache/diagnostics.go
langserver/cache/document.go
langserver/cache/position.go
langserver/cache/yaml.go
langserver/diagnostics.go

Fixes #49, Fixes #34, Fixes #30

Yaml support

---

README.md
langserver/cache/position.go
langserver/config.go
langserver/hover.go
langserver/server.go

Show doc strings for metrics on hover.
Fixes #33

Metric docs

---

README.md
langserver/completion.go
langserver/general.go
langserver/hover.go
langserver/notImplemented.go

This PR add completion for metric names to the language server.
Fixes #5

Completion for Metric names

---

langserver/cache/compile.go
langserver/cache/document.go
langserver/cache/document_test.go
langserver/cache/yaml.go

Add context expiration tests

---

langserver/cache/yaml.go

Consider yaml paths when deciding whether something is a PromQL query

---

langserver/cache/cache.go
langserver/cache/cache_test.go
langserver/cache/compile.go
langserver/cache/diagnostics.go
langserver/cache/document.go
langserver/cache/document_test.go
langserver/cache/position.go
langserver/cache/yaml.go
langserver/completion.go
langserver/diagnostics.go
langserver/hover.go
langserver/langserver_test.go
langserver/textSync.go

Introduce DocumentHandle Type

---

.circleci/config.yml

Fix release builds

---

.circleci/config.yml

CI: enable build cache

---

langserver/config.go

Change config path to PromQL

---

langserver/general.go

Fixes https://github.com/slrtbtfs/vscode-promql/issues/10

Add more commit charakters for completion

---

README.md

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

fix typo langauge -> language

---

cmd/promql-langserver/promql-langserver.go
langserver/cache/cache.go
langserver/cache/cache_test.go
langserver/config.go
langserver/diagnostics.go
langserver/general.go
langserver/headlessClient.go
langserver/server.go
langserver/textSync.go
rest/doc.go
rest/handler.go
stateless/handler.go

WIP: Add a stateless API for language server features

---

Makefile
rest/handler.go

Run linter on rest package

---

Makefile

Include vendored modules in tests

---

langserver/completion.go

Stop offering completions for already filtered labels

---

langserver/hover.go

hover: Fix handling of empty metric names

---

websocket/websocket.go

Solves https://github.com/prometheus/prometheus/pull/6872#discussion_r384440246

Put websocket handler into separate package

---

CONTRIBUTING.md

Add instructions about manual testing

---

langserver/completion.go
langserver/hover.go
langserver/server.go

Signed-off-by: Drumil Patel <drumilpatel720@gmail.com>
Fixes #76 
Add completion after #122

Use metadata apis for completion

---

CONTRIBUTING.md

Add build instructions

---

langserver/hover.go

Signed-off-by: Drumil Patel <drumilpatel720@gmail.com>
Fixes #132

Use documented type for promql type on hover

---

.circleci/config.yml

Update go compiler to 1.14

---

.gitignore
Makefile
cmd/promql-langserver/promql-langserver.go
langserver/completion.go
langserver/general.go
langserver/hover.go
langserver/server.go
prometheus/client.go
prometheus/compatible.go
prometheus/empty.go
prometheus/not_compatible.go
rest/handler.go

This PR contains the new interface for the custom prometheus client.
The langserver is now using the custom prometheus client.
That's the first PR to resolve the issue #134

Abstract the way to contact the prometheus server

---

.circleci/config.yml
.github/workflows/golangci-lint.yml
.golangci.yml
Makefile
README.md
cmd/promql-langserver/promql-langserver.go
langserver/cache/document.go
langserver/cache/document_test.go
langserver/cache/position.go
langserver/cache/waitgroup.go
langserver/cache/yaml.go
langserver/completion.go
langserver/config.go
langserver/definition.go
langserver/diagnostics.go
langserver/general.go
langserver/hover.go
langserver/langserver_test.go
langserver/notImplemented.go
langserver/server.go
langserver/signature.go
langserver/textSync.go
prometheus/client.go
prometheus/compatible.go
prometheus/empty.go
prometheus/not_compatible.go
rest/handler.go
websocket/websocket.go

Add golangci-lint Github Action

---

README.md

Use pkg.go.dev for documentation badge

---

cmd/promql-langserver/promql-langserver.go
go.mod
langserver/config.go
langserver/config_test.go
langserver/headlessClient.go
langserver/server.go
rest/handler.go

Use go-kit/log for REST API

---

README.md

It's already been in the official package control channel. 🎉

Introduce Sublime Text plugin LSP-promql

---

langserver/completion.go

This PR introduces Fuzzy completion matching for Function names,Label values, Label names and Aggregators.

Fuzzy completion matching for other types

---

langserver/completion.go
langserver/hover.go
langserver/server.go
prometheus/client.go
prometheus/compatible.go
prometheus/empty.go
prometheus/metadata_service.go
prometheus/not_compatible.go
rest/handler.go

* Change the method name according to the PR comments: https://github.com/prometheus/prometheus/pull/6872#discussion_r436964270
* Remove duplicate element when getting labelName

Update prometheus client implementation

---

langserver/signature.go

Fixes #166 
Screenshot:
Screenshot for the special case of variable argument numbers:
cc @juliusv

Correctly set activeParameter for signatureHelp

---

cmd/promql-langserver/promql-langserver.go
rest/handler.go

Clarify documentation

---

go.mod
go.sum

Signed-off-by: Augustin Husson <husson.augustin@gmail.com>

Bump github.com/prometheus/client_golang from 1.7.0 to 1.7.1

---

.goreleaser.yml

Signed-off-by: Augustin Husson <husson.augustin@gmail.com>

fix docker images name

---

langserver/config.go

use a proper struct to decode the config
